services:
  jenkins:
    image: jenkins-kubectl:latest
    container_name: jenkins
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./jenkins-k8s-manifests/kube-config.yaml:/home/jenkins/.kube/config
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  jenkins_home: