services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    privileged: true
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    depends_on:
      - registry
    extra_hosts:
      - "host.docker.internal:host-gateway"

  registry:
    image: registry:2
    container_name: local-registry
    volumes:
      - registry_data:/var/lib/registry
      - ./certs:/certs
    ports:
      - "5000:443"
    environment:
      REGISTRY_HTTP_ADDR: "0.0.0.0:443"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/registry.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/registry.key"
    restart: always

volumes:
  jenkins_home:
  registry_data: