services:
  jenkins:
    image: jenkins-kubectl:latest
    container_name: jenkins
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /jenkins-k8s-manifests/kube-config.yaml:/home/jenkins/.kube/config
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    depends_on:
      - registry
    extra_hosts:
      - "host.docker.internal:host-gateway"

  registry:
    image: registry:2
    container_name: local-registry
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    volumes:
      - registry_data:/var/lib/registry
      - ./auth:/auth
    ports:
      - "5000:5000"
    restart: always

volumes:
  jenkins_home:
  registry_data:
