services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker-network
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always

  registry:
    image: registry:2
    container_name: local-registry
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - docker-network
    ports:
      - "5000:5000"
    restart: always

volumes:
  jenkins_home:
  registry_data:

networks:
  docker-network:
