apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  labels:
    name: jenkins-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-cd-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - deployments
  - services
  - configmaps
  - secrets
  - replicasets
  verbs:
  - create
  - delete
  - patch 
  - update 
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-cd-role-binding
  namespace: default
roleRef:
  kind: Role
  name: ci-cd-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: jenkins-sa
    namespace: default
